fintech_transaction_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: SE12433.ap-southeast-1
      user: CongVu18
      password: Setimduocviec68!
      role: ACCOUNTADMIN
      database: FINTECH_ANALYTICS
      warehouse: FINTECH_WH
      schema: RAW
      threads: 6
      client_session_keep_alive: false